/**
 * Event Type Constants
 *
 * Classification of all events logged to the audit trail.
 * Each event represents an atomic action in the system.
 */
export const EventType = {
	// Lead lifecycle events
	LEAD_IMPORTED: "LEAD_IMPORTED",
	LEAD_QUEUED: "LEAD_QUEUED",
	LEAD_SKIPPED: "LEAD_SKIPPED",
	LEAD_UNSUBSCRIBED: "LEAD_UNSUBSCRIBED",

	// Verification events
	VERIFICATION_STARTED: "VERIFICATION_STARTED",
	VERIFICATION_PASSED: "VERIFICATION_PASSED",
	VERIFICATION_FAILED: "VERIFICATION_FAILED",
	VERIFICATION_RISKY: "VERIFICATION_RISKY",

	// Email sending events
	EMAIL_SENDING: "EMAIL_SENDING",
	EMAIL_SENT: "EMAIL_SENT",
	EMAIL_FAILED: "EMAIL_FAILED",

	// SES delivery/tracking events (from SQS)
	EMAIL_DELIVERED: "EMAIL_DELIVERED",
	EMAIL_REJECTED: "EMAIL_REJECTED",
	EMAIL_DELAYED: "EMAIL_DELAYED",
	EMAIL_OPENED: "EMAIL_OPENED",
	EMAIL_CLICKED: "EMAIL_CLICKED",
	RENDERING_FAILURE: "RENDERING_FAILURE",
	SUBSCRIPTION_CHANGED: "SUBSCRIPTION_CHANGED",

	// Feedback events (from AWS SQS)
	BOUNCE_RECEIVED: "BOUNCE_RECEIVED",
	COMPLAINT_RECEIVED: "COMPLAINT_RECEIVED",

	// Campaign lifecycle events
	CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
	CAMPAIGN_STARTED: "CAMPAIGN_STARTED",
	CAMPAIGN_PAUSED: "CAMPAIGN_PAUSED",
	CAMPAIGN_RESUMED: "CAMPAIGN_RESUMED",
	CAMPAIGN_ABORTING: "CAMPAIGN_ABORTING",
	CAMPAIGN_ABORTED: "CAMPAIGN_ABORTED",
	CAMPAIGN_COMPLETED: "CAMPAIGN_COMPLETED",
	CAMPAIGN_ERROR: "CAMPAIGN_ERROR",

	// System events
	SYSTEM_STARTUP: "SYSTEM_STARTUP",
	SYSTEM_RECOVERY: "SYSTEM_RECOVERY",
	SYSTEM_ERROR: "SYSTEM_ERROR",
	LOCK_ACQUIRED: "LOCK_ACQUIRED",
	LOCK_RELEASED: "LOCK_RELEASED",
	LOCK_BLOCKED: "LOCK_BLOCKED",
} as const;

export type EventTypeValue = (typeof EventType)[keyof typeof EventType];

/**
 * Orchestrator Action Constants
 *
 * Actions that can be sent to the orchestrator function.
 */
export const OrchestratorAction = {
	START: "START",
	PAUSE: "PAUSE",
	RESUME: "RESUME",
	ABORT: "ABORT",
} as const;

export type OrchestratorActionType = (typeof OrchestratorAction)[keyof typeof OrchestratorAction];
