/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsStagingRouteImport } from './routes/leads.staging'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsStagingRoute = LeadsStagingRouteImport.update({
  id: '/staging',
  path: '/staging',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/leads/staging': typeof LeadsStagingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/leads/staging': typeof LeadsStagingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/leads/staging': typeof LeadsStagingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leads'
    | '/login'
    | '/logs'
    | '/settings'
    | '/templates'
    | '/leads/staging'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leads'
    | '/login'
    | '/logs'
    | '/settings'
    | '/templates'
    | '/leads/staging'
  id:
    | '__root__'
    | '/'
    | '/leads'
    | '/login'
    | '/logs'
    | '/settings'
    | '/templates'
    | '/leads/staging'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/staging': {
      id: '/leads/staging'
      path: '/staging'
      fullPath: '/leads/staging'
      preLoaderRoute: typeof LeadsStagingRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsStagingRoute: typeof LeadsStagingRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsStagingRoute: LeadsStagingRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
